### ISSUE TITLE
Add Support for Postgres v18 and DataVolume

### ISSUE THREAD

**Issue by maperz** [dotnet/aspire#11710]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Last week, version 18 of Postgres was released, and with it, exciting new features.
When trying to integrate the specific new version with Aspire (e.g. via  `.WithImageTag("18.0-alpine")`)
Issues occur when trying to persist the database via `WithDataVolume`.

This occurs because the new Postgres folder structure and storing database data under a version specific `/var/lib/postgresql/18/data` (notice the new */18/* part of the path).

The specific error is the following:

> Failed to start Container {"Container": "/app-db-a5f7ed39", "Reconciliation": 9, "ContainerID": "6abfc32df9b3", "ContainerName": "app-db-a5f7ed39", "error": "status of container 'app-db-a5f7ed39' is 'created' (was expecting 'running'), error: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/var/lib/docker/volumes/ipseweb.apphost-a5f7ed3973-app-db-data/_data\" to rootfs at \"/var/lib/postgresql/data\": change mount propagation through procfd: open o_path procfd: open /var/lib/docker/overlay2/565bae96a29896f38a93152422eb700cb397ae3e46172720b7ed0b37fc8e3ea7/merged/var/lib/postgresql/data: no such file or directory: unknown\ndocker command 'StartContainers' returned with non-zero exit code 1\nnot all requested objects were returned\nonly 0 out of 1 containers were successfully started"}

A current workaround for now is simply extending the resource builder with a version-specific volume mapping:

```
public static class Postgres18BuilderExtensions
{
    public static IResourceBuilder<PostgresServerResource> WithDataVolumeForV18(
        this IResourceBuilder<PostgresServerResource> builder, string? name = null, bool isReadOnly = false)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithVolume(name ?? VolumeNameGenerator.Generate(builder, "data"),
            "/var/lib/postgresql/18/data", isReadOnly);
    }
}
```

Moving on, it will be required to either override the default `WithDataVolume` with a specific version or let Aspire infer the version from the image tag used.

### Describe the solution you'd like

Postgres 18+ should support `.WithDataVolume()`  as previous versions did.

The correct data volume shall be used with Postgres versions 18+.
With the new version, the path should be "/var/lib/postgresql/18/data".

**Comment by joperezr** [comment]
Thanks for logging this and sorry for the lack of activity here. Can you please try the latest nightly build to make sure this is fixed? We should have fixed it via https://github.com/dotnet/aspire/pull/12459 which included this change: https://github.com/dotnet/aspire/pull/12459/files#diff-b3f4063a458774586ef21dd8ea2fad2ae08678b0aee23099961aa1efb3974e71

Marking as closed for now as this has been merged in main for a while, but please feel free to reopen if you are trying nightly builds and this still doesn't work as expected.

**Comment by yasmoradi** [comment]
I just tested with `13.1.0` and the problem still exists
Can confirm the following workaround works for me:
```csharp
    public static IResourceBuilder<PostgresServerResource> WithV18DataVolume(
        this IResourceBuilder<PostgresServerResource> builder, string? name = null, bool isReadOnly = false)
    {
        return builder.WithVolume(name ?? VolumeNameGenerator.Generate(builder, "data"),
            "/var/lib/postgresql/18/docker", isReadOnly);
    }
```

**Comment by joperezr** [comment]
I am so sorry @ysmoradi, you are correct, we had to [revert ](https://github.com/dotnet/aspire/pull/13575) the fix right before shipping as we wanted a bit more time to discuss what the right behavior is specifically for the nodatachecksums argument that was being added. We can of course separate this fix for the data volume as well, but I'm going to reopen this issue and assign it to 13.2 to make sure we have a better solution in our next release.

**Comment by ysmoradi** [comment]
Just to be clear, by setting milestone to 13.2, it means that it's not resolved in recent 13.1.1 as well, right?

**Comment by jakoss** [comment]
I'm testing the 13.2 and it is still not working, maybe it's custom image?

```
.WithImage("pgvector/pgvector")
.WithImageTag("pg18-trixie")
```

In 13.2 release notes there is an entry about fix: 

<img width="1135" height="261" alt="Image" src="https://github.com/user-attachments/assets/6eba699b-4b24-4059-9b3b-79fbf83626f5" />
But milestone here is still 13.3, confusing

**Comment by yasmoradi** [comment]
I'm also using custom image, `pgvector/pgvector`, it's somewhat popular

**Comment by jakoss** [comment]
I peaked at the implementation, version check check is directly based on tag and pgvector tag is not compatible with that logic, so i guess this is probably a separate issue. Current code for version detection:
```csharp
/// <summary>
    /// Gets the appropriate PostgreSQL data directory path based on the image version.
    /// </summary>
    /// <remarks>
    /// PostgreSQL 18+ changed the data directory from /var/lib/postgresql/data to /var/lib/postgresql.
    /// See https://github.com/docker-library/postgres/pull/1259 for more information.
    /// </remarks>
    internal static string GetPostgresDataDirectoryPath(IResourceBuilder<PostgresServerResource> builder)
    {
        if (builder.Resource.Annotations.OfType<ContainerImageAnnotation>().LastOrDefault() is { } imageAnnotation)
        {
            var tag = imageAnnotation.Tag ?? PostgresContainerImageTags.Tag;
            if (TryParsePostgresMajorVersion(tag, out var majorVersion) && majorVersion >= 18)
            {
                return "/var/lib/postgresql";
            }
        }

        return "/var/lib/postgresql/data";
    }

    /// <summary>
    /// Attempts to parse the PostgreSQL major version from an image tag.
    /// </summary>
    /// <param name="tag">The image tag (e.g., "17.6", "18.1", "18-alpine", "latest").</param>
    /// <param name="majorVersion">The parsed major version number, if successful.</param>
    /// <returns><see langword="true"/> if the major version was successfully parsed; otherwise, <see langword="false"/>.</returns>
    internal static bool TryParsePostgresMajorVersion(string tag, out int majorVersion)
    {
        majorVersion = 0;

        if (string.IsNullOrWhiteSpace(tag))
        {
            return false;
        }

        // Handle tags like "18.1-alpine", "17.6-bookworm", etc.
        var versionPart = tag.Split('-')[0];

        // Handle tags like "18.1", "17", etc.
        var parts = versionPart.Split('.');

        return parts.Length > 0 && int.TryParse(parts[0], out majorVersion) && majorVersion > 0;
    }
```

TryParsePostgresMajorVersion in current form does not work since pg_vector have pg prefix in the tag

**Comment by joperezr** [comment]
As part of a triage pass for 13.3 (shipping next week), I'm tightening the milestone to focus on regressions and ship-blocking work. This issue has been deprioritized from previous milestones, so I'm moving it out of 13.3 to the Backlog for now.

If you feel this should still be considered for 13.3, please speak up here and we can reassess.
