### ISSUE TITLE
[WebToolsE2E][Aspire] The new changes of contents in aspire dashboard are not localized in non-ENU OS.

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#5382]
**REGRESSION**
1. Not a regression in aspire 8.1.0 because this are new changes in aspire 8.2.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 22h2 KOR
2. Install VS 17.11.1
3. Install Aspire 8.2.0

**REPRO STEPS**

1. Create Aspire Starter App
2. Build solution and run the project

**ACTUAL**

1. In Resources module these are the contents that are not localized

- The "Open in text visualizer" option in Source

![image](https://github.com/user-attachments/assets/266282aa-b558-4cb5-bb12-c9e94276a857)

- The "Sort" & "Resize" option in [Type, Name, State, Start time]

![image](https://github.com/user-attachments/assets/0a4cba79-66cb-4e4c-8900-63c09028add5)

- The "Column width (in pixels) in [Source, Endpoints, Logs, Details]

![image](https://github.com/user-attachments/assets/8a08b040-2422-4741-85da-3749612aba07)

2. In Console and Metrics module, the (None) option is not localized
![image](https://github.com/user-attachments/assets/4887d57e-dade-4958-b3a8-f0e11da1c8e2)

3. The "Resource" in [Console, Structured, Traces, Metrics] is not localized
![image](https://github.com/user-attachments/assets/5540b23c-3356-4a92-b3bd-f6738f9c4ef6)

**EXPECTED**
The new changes for the contents of aspire dashboard should be localized.

**Comment by kvenkatrajan** [comment]
@adamint - for when you are back - please have a look

**Comment by adamint** [comment]
@kvenkatrajan these strings were added so recently that I don’t think we have updated translations yet. I’ll keep the issue open and check in a few weeks but should resolve itself.

**Comment by kvenkatrajan** [comment]
@balachir  - FYI - new strings - pending translations from loc team.

**Comment by vmykagapuz** [comment]
These new changes in Aspire 9.0 are also not localized
![image](https://github.com/user-attachments/assets/1ae046a0-8e13-42c8-8801-90ba74333c9e)

**Comment by drewnoakes** [comment]
@vmykagapuz those strings were also added quite recently, and it can take a while for translations to be made available.

Could you please recheck these on the latest build and let us know if they still occur.

Note also that the "Column width (in pixels)" text (and probably "Sort" and "Resize") come from the Blazor Fluent UI library, where they were recently added. If they're still not localised then we should open an issue in https://github.com/microsoft/fluentui-blazor/issues.

**Comment by vmykagapuz** [comment]
@drewnoakes I verified this issue on the latest build and still occur in Aspire 9.0 Preview 4

**Comment by vmykagapuz** [comment]
[#2710](https://github.com/microsoft/fluentui-blazor/issues/2710) opened this issue in https://github.com/microsoft/fluentui-blazor/issues related to this bug.

**Comment by adamint** [comment]
Loc PRs are now coming in as usual.

@vmykagapuz it may take some time for a release to occur, but if you test using the main branch in this repository, you will see the translated strings. Closing

**Comment by vmykagapuz** [comment]
> Loc PRs are now coming in as usual.
> 
> @vmykagapuz it may take some time for a release to occur, but if you test using the main branch in this repository, you will see the translated strings. Closing

Thanks. I verified that all the strings mentioned in this bug is already localized using 17.12 P3 in main brain repository with Aspire 9.0

**Comment by kvenkatrajan** [comment]
[heart]         Kay Venkatrajan reacted to your message:
________________________________
