### ISSUE TITLE
Container failing to start with nonsensical error

### ISSUE THREAD

**Issue by afscrome** [dotnet/aspire#6787]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm intermittently seeing a container fail to start - both with the dashboard and the test host.
```
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      failed to start Container {"Container": {"name":"REDACTED-nhxmstre"}, "Reconciliation": 20, "ContainerID": "5b95e829bf762d6c922ca9400f9b1d774aeac678624a0a5212c831c7b85fefad", "error": "status of container 5b95e829bf762d6c922ca9400f9b1d774aeac678624a0a5212c831c7b85fefad is 'exited' (was expecting 'exited')"}
```

In particular the error is nonsensical - how is it an error to expect state `exited` and the actual state to be `exited`?
> status of container {0} is 'exited' (was expecting 'exited')"}

Another curious thing I see with this error is the resource logs for this container print the container id several times in a row before failing.

![Image](https://github.com/user-attachments/assets/8031e80e-7b29-4258-9157-3106c68f9bcf)

### Expected Behavior

Ideally I'd like the error to not happen at all.  However if this error is raised, I'd like it to explain what the problem is - the current error text is nonsensical.

I'd also expect any errors from the Container Reconciler to be printed out to the resource logs in the aspire dashboard as from the dashboard there's no indication of why the resource failed to start i.e.
![Image](https://github.com/user-attachments/assets/176f573a-4b64-4b5a-924e-b0240840a252)

### Steps To Reproduce

Inconsistent I'm afraid 😭.

### .NET Version info

.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  6.0.428 [C:\Program Files\dotnet\sdk]
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by dbreshears** [comment]
Thanks, will need to look into.  Are you using Docker as container runtime?

**Comment by afscrome** [comment]
Yes - Docker Desktop 4.35.1 (173168) specifically.

**Comment by joperezr** [comment]
Thanks for logging this @afscrome. Can you please share which version of Aspire you are using? You can tell by the version of the package reference to Aspire.Hosting.AppHost in your apphost project. We think that this is an issue that was in 9.0 but has been fixed in main, so would you be able to try the latest 9.1*-* build?

**Comment by afscrome** [comment]
I've worked out a more reliable repo - it seems to happen when you have a container that exists very quickly.  I can fairly reliably (but not always) reproduce with:

```cs
builder.AddContainer("quick-exit", "mcr.microsoft.com/dotnet/runtime-deps", "9.0");
```

I was previsouly usign 9.0.0 but can still reproduce after upgrading to the 9.1 preview.

```xml
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0-preview.1.24578.4" />

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0-preview.1.24578.4" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.1.0-preview.1.24578.4" />
  </ItemGroup>
```

**Comment by lochsenfeld** [comment]
I am using podman as container runtime with openfga/cli image which basically returns instant with Code 0.
I am using Aspire 9.0. I basically have the exact same behaviour:

![Image](https://github.com/user-attachments/assets/337c1da0-3d45-4ca5-aafb-452c430d2bd2)

![Image](https://github.com/user-attachments/assets/e6b79e7d-320e-4eef-ad3d-c4243f82b8fd)

```
builder.AddResource(new OpenFgaCliResource(name))
            .WithImage("openfga/cli")
            .WithImageRegistry("docker.io")
            .WithImageTag("v0.6.2")
            .WithArgs("store", "import", "--file", "/model/store.fga.yaml")
            .WithEnvironment("XDG_CONFIG_HOME", "/")
            .WithEnvironment("HOME", "/")
            .WithReference(openfga)
            .WaitFor(openfga);
```

You can probably achieve the same when calling -help as Args. The container exits with code 0 according to podman as expected. Aspire seems to have a bug where it compares the exit codes.

**Comment by karolz-ms** [comment]
Should be fixed by https://github.com/dotnet/aspire/pull/6931
