### ISSUE TITLE
Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0] : could not detach network from the container

### ISSUE THREAD

**Issue by yizuyue** [dotnet/aspire#6959]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

<img width="1782" alt="Image" src="https://github.com/user-attachments/assets/ad94cd00-a873-4e43-bcc5-ccbbf9630910" />
M1 Pro, Aspire program cannot start when creating containers in Dockers. What is the reason for this? The error message is a network problem. Did you use a none type network?

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 9.0.0+01ed51919f8df692ececce51048a140615dc759d
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: /Users/y/RiderProjects/clean-architecture/AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: http://localhost:15210
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at http://localhost:15210/login?t=90090534-1cf5-4e71-86e7-9cc99f2392c1
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not detach network from the container       {"Container": {"name":"cache-tqmvdbuy"}, "Reconciliation": 3, "ContainerID": "e8fe3c49e4868a3de1d43de4cda1c2e2dafdb570343375376c8f8c498cb08f26", "Network": "", "error": "docker command 'DisconnectNetwork' returned with non-zero exit code 1: command output: Stdout: '' Stderr: 'Error response from daemon: page not found\n'"}
```

### .NET Version info

.NET 8.0

**Comment by OceanYuss** [comment]
My problem, like yours, has not been solved yet

**Comment by OceanYuss** [comment]
According to the guidance, the container network was checked and the disconnect command was manually executed, but the error still persists

**Comment by karolz-ms** [comment]
From the error message looks like the network ID for the detach operation is empty. This should not happen. My guess: we are inspecting the container right after creation and it is not connected to the bridge network yet. @danegsta have you seen this?

**Comment by OceanYuss** [comment]
Thank you sir, this issue has been resolved. I used version 8.0.2 and upgraded to version 9.0.0 without encountering this problem
&nbsp;


世风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Karol ***@***.***&gt;; 
发送时间: 2024年12月24日(星期二) 凌晨5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnet/aspire] Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0] : could not detach network from the container (Issue #6959)














 
From the error message looks like the network ID for the detach operation is empty. This should not happen. My guess: we are inspecting the container right after creation and it is not connected to the bridge network yet. @danegsta have you seen this?

**Comment by OceanYuss** [comment]
Thank you sir, this issue has been resolved. I used version 8.0.2 and upgraded to version 9.0.0 without encountering this problem

**Comment by Hygge** [comment]
thank you，It turns out the version is causing the problem

**Comment by Yzy-pg** [comment]
@OceanYuss @karolz-ms Thank you, after I upgraded the version, it is now working properly

**Comment by karolz-ms** [comment]
That is great! But let's keep this open because looking at the source code, I do believe we might still have an issue mentioned above https://github.com/dotnet/aspire/issues/6959#issuecomment-2560315076

**Comment by karolz-ms** [comment]
After poking around some more I am pretty sure the error seen here must have been caused by processing of the result of `container inspect` command and that this has been fixed for good..
